### ISSUE TITLE
Bootstrap is failing

### ISSUE THREAD

**Issue by tmbrbr** [SAP/project-foxhound#140]
Currently builds are failing to successfully bootstrap the build toolchains with the following error:

```
ERROR!!!!!! Could not find artifacts for a toolchain build named `toolchain-linux64-clang`. Local commits, dirty/stale files, and other changes in your checkout may cause this error. Make sure you are on a fresh, current checkout of mozilla-central. Beware that commands like `mach bootstrap` and `mach artifact` are unlikely to work on any versions of the code besides recent revisions of mozilla-central.
```

This is caused by building slightly different commits compared to those supported by Mozilla. As I understand it, the build toolchains are selected via the hashes over a number of version files in the source tree. If some of these files are different (even if nothing to do with tainting) the tools are not found and the download fails. This seems to be a common problem that has been around in most versions of Firefox since v98.

## Workaround
First checkout the latest upstream firefox release (or the https://github.com/SAP/project-foxhound/tree/firefox-release branch) and download the tools via ```./mach bootstrap```. Then switch to the foxhound branch (ie main) and build **without** the ```enable-bootstrap``` compiler option.

## To Do
- [ ] Update build documentation to reflect this
- [x] Update the Github actions scripts to first checkout (and cache) the build tools (located in ```~/.mozbuild```, then copy them into the job doing the foxhound build.
- [ ] Remove enable-bootstrap flag from default config

**Comment by unqrf** [comment]
Note that taintfox_mozconfig_ubuntu already has --enable-bootstrap, so you'd want to remove that to apply the workaround.

**Comment by tmbrbr** [comment]
> Note that taintfox_mozconfig_ubuntu already has --enable-bootstrap, so you'd want to remove that to apply the workaround.

Good catch, I have removed the config option in #176
