### ISSUE TITLE
Mozilla blocks Pull Requests

### ISSUE THREAD

**Issue by tmbrbr** [SAP/project-foxhound#187]
As Mozilla doesn't use Github pull requests to merge new features, they have a GitHub action to automatically close pull requests:

https://github.com/SAP/project-foxhound/blob/main/.github/workflows/close-pr.yml

This should be removed / disabled as it is causing pull request build checks to fail.

**Comment by leeN** [comment]
It sounds like you could [disable the workflow in the UI](https://docs.github.com/en/actions/using-workflows/disabling-and-enabling-a-workflow). I do not have sufficient permission, so the option is not there for me on [here](https://github.com/SAP/project-foxhound/actions/workflows/close-pr.yml).

This might be easier than modifying the .yml and running into merge conflicts down the line.

**Comment by tmbrbr** [comment]
Disabling manually seems to work, thanks!

I am always happy to avoid merge conflicts! 😄
