### ISSUE TITLE
Failing Tests for DOMParser

### ISSUE THREAD

**Issue by tmbrbr** [SAP/project-foxhound#194]
There are some DOMParser tests which are failing:

```
./mach test --log-xunit=taint_test_output.xml --headless taint/test/mochitest/test_dom_parser.html
```
 In particular, the XML parser is failing to propagate tainting information:

```JavaScript
const tainted_xml_str = "<warning>" + tainted_str + "</warning>";
const doc2 = parser.parseFromString(tainted_xml_str, "application/xml");

check_tainted(doc2.documentElement.textContent);  // Failing!
```

**Comment by leeN** [comment]
I have looked into this a bit, and as far as I can see, fixing this is a significant amount of effort. As far as I found, Firefox delegates XML parsing to [expat, a third-party library written in C](https://github.com/SAP/project-foxhound/blob/main/parser/htmlparser/nsExpatDriver.h). Now, this is possible to modify to be taint aware, but I am not quite sure whether it is a sensible time investment.

**Comment by tmbrbr** [comment]
Thanks for looking into this! Given the time investment, I am not sure this is worthwhile unless there is an explicit need for it.

**Comment by leeN** [comment]
I'll close this as WONTFIX based on our call yesterday. If somebody really wants to do this she can reopen an issue and contribute a PR I suppose :)
