### ISSUE TITLE
Add context/path information to JSON-based string accesses

### ISSUE THREAD

**Issue by vladidx** [SAP/project-foxhound#199]
JSON objects are often created from XHR responses and then flowing into the DOM (potentially without escaping).
It would be quite helpful to know the path/context of the tainted string within the JSON object, e.g. as part of the arguments:
![image](https://github.com/SAP/project-foxhound/assets/29225968/d68ef958-3492-46ea-a2e2-1e4287173e41)

Ideally, the context information would be a kind of XPath for JSON as described [here](https://www.ietf.org/archive/id/draft-goessner-dispatch-jsonpath-00.html).

**Comment by tmbrbr** [comment]
I'm working on a fix for this which would give:

```
"?.d.BookingExtension.BookingComment"
```

as the JSON Path for the above example. Would this be sufficient?

**Comment by vladidx** [comment]
Yes, that would be already sufficient, thanks.

**Comment by tmbrbr** [comment]
Ooops, just checked the spec again, I guess it should be a leading ```$``` instead of a ```?```

**Comment by vladidx** [comment]
👍

**Comment by tmbrbr** [comment]
This is implemented with #200
