### ISSUE TITLE
Make matching Playwright version available for automation

### ISSUE THREAD

**Issue by leeN** [SAP/project-foxhound#212]
I was thinking about how we can improve the onboarding experience, as there is no longer a tutorial on how to build Foxhound with Playwright integration.

Internally, I have a script that builds and adds the Playwright nits automatically. One difficulty is that it requires some configuration, as we do not expose the current Playwright version in a way that a shell script can easily read.

I was wondering if we could simplify this, e.g., by having a .PLAYWRIGHT_VERSION file inside the foxhound repository, which contains the currently matching release. If that messes with the (completely insane) `mach bootstrap` logic, we can also add this to the mozconfig as `PLAYWRIGHT_VERSION="release-1.42"` or similar. This should hopefully not mess with any mozbuild aspects. Compared to the first suggestion, this increases the maintenance effort significantly, as you have to touch a bunch of files for each change.

**Comment by leeN** [comment]
I have uploaded the build script [here](https://github.com/leeN/project-foxhound-builder) but it still needs a bit of messing around with. If you consider this something we want to include in foxhound directly, we can move it to this repo.

**Comment by tmbrbr** [comment]
Very nice, I think would be super useful to make playwright builds easier.

I would be in favour of *not* integrating into the mozconfig / mach build system to avoid higher maintainence costs.

@leeN could you prepare a PR which adds the suggested .PLAYWRIGHT_VERSION file? I'm also happy to include the script in the main repo as well.

**Comment by tmbrbr** [comment]
This can be closed, right? It should have been integrated in #225

**Comment by leeN** [comment]
Yes!
