### ISSUE TITLE
Add Hall of Fame and Paper List

### ISSUE THREAD

**Issue by tmbrbr** [SAP/project-foxhound#214]
As Foxhound is gaining some traction in the academic community, it would be great to have a list of papers in the README.md where it has been used.

At the same time, a list of GitHub users who have made significant contributions would also be nice to acknowledge the hard work put in!

**Comment by leeN** [comment]
That sounds like a good idea :) I'm collecting papers using Foxhound on [our homepage](https://www.tu-braunschweig.de/ias/tooling), FP Tracer is still missing due to PETS not having provided us with a DOI yet (?).

**Comment by tmbrbr** [comment]
Once merged, #228 will partially implement this (list of papers).

**Comment by leeN** [comment]
I think this is complete now? Contributors are listed in the readme, papers are in the Wiki :)
