### ISSUE TITLE
Cannot build Foxhound release v121.0

### ISSUE THREAD

**Issue by eleumasc** [SAP/project-foxhound#222]
Good morning,
I cannot build the release in the subject (https://github.com/SAP/project-foxhound/releases/tag/v121.0), getting the error in the image (sorry for the screenshot), using the version of rust downloaded automatically by bootstrap, while using the suggested rust version 1.66 does not bootstrap. I cannot even bootstrap the corresponding firefox-release (https://github.com/SAP/project-foxhound/commit/a32b8662993085139ac91212a297123b632fc1c0). I am running the build process in a fresh virtual machine with Ubuntu 22.04.4 LTS (Jammy Jellyfish).  We were able to build previous releases of Foxhound (v116.0) without issues, following the indicated procedure in the same environment.

![image](https://github.com/user-attachments/assets/517add82-5888-4ef1-bb20-282670de6356)

**Comment by eleumasc** [comment]
Yes, the bootstrap stage fails for firefox-release (see screenshot below). However, building the main branch with ./mach build also gives the compilation error in the above image.

![image](https://github.com/user-attachments/assets/753c7682-852d-47b3-80b9-398eb245be91)

**Comment by LuySeiwert** [comment]
Hi, have you tried running the bootstrap with a recent rust version and downgrading to 1.66 afterwards? I was able to build the main branch without playwright this way. For some reason this does not work when I try to build foxhound with playwright, in that case I am running into the same issue currently. 

Unless, I am misunderstanding and the release also has the playwright integration.

If I remember correctly, I also ran into the 'toolchain-linux64-clang' error at one point and was able to fix it by installing clang, so that might be worth a try, if it's not installed yet.

**Comment by eleumasc** [comment]
@LuySeiwert thank you for the suggestions. Unluckily, I am still not able to build Foxhound, even without Playwright. I am using Ubuntu 22.04 LTS, I installed clang and the Firefox building environment. From main, mach bootstrap succeeds with rust 1.80. Then, mach build fails with the error in the posted issue. If I retry mach build after downgrading rust to 1.66, it fails with "To compile Rust language sources please install at least version 1.70.0".

**Comment by LuySeiwert** [comment]
I think you can try once more with version 1.70.0. If I understand correctly a recent version of Rust breaks backwards compatibility with various libraries, such as the time library https://github.com/rust-lang/rust/issues/127343. So, while 1.66 is too old and 1.80 is too new, 1.70.0 worked for me: Using a Ubuntu 24.04 virtual machine, with Rust 1.70.0 I can build foxhound with playwright using the script https://github.com/leeN/project-foxhound-builder from David Klein (for other environments such as my other Ubuntu 22.04 vm, this did not yet work, for some reason...)

If I understood the issue correctly the actual solution would be to update the rust dependencies, specifically this time library, although I haven't figured out how to do so yet. It seems you can't just run `cargo update`, but you'd also have to vendor the updates https://firefox-source-docs.mozilla.org/build/buildsystem/rust.html#third-party-crate-dependencies.

**Comment by eleumasc** [comment]
After upgrading rust to 1.70, everything works in Ubuntu 22.04 LTS, even the Playwright integration. This sweet spot between rust versions blows my mind 🤯

Regarding the build process, I run https://github.com/leeN/project-foxhound-builder/blob/master/build.sh (thanks to @leeN for providing this script), with the exception of cloning this repo and checking out the release commit with the `--depth 1` option of git (definitely faster than cloning the repo with the whole history).

Thank you everyone for your support, I close this issue for now.

**Comment by tmbrbr** [comment]
@eleumasc great that the build is now working!

It's true that getting the right rust version is a bit of an art, this is probably something we should document and/or automate better.

Thanks @leeN again for the build script and @LuySeiwert for your support here!
