### ISSUE TITLE
Add a Github Action for playwright patching.

### ISSUE THREAD

**Issue by tmbrbr** [SAP/project-foxhound#230]
Currently we have a GitHub action which builds and tests SpiderMonkey. Unfortunately complete browser builds always timeout or run out of memory.

One thing we could do is add a GitHub action which tests playwright compatibility by running the preparation parts of the build.sh script, without building.

With this we could catch any incompatibility errors before merging.

**Comment by leeN** [comment]
That sounds like a good idea. I will assign this to me, as this should be a quick implementation. I think it should be workable to fit in some spare time in this way too busy week or when I'm traveling next week. So I'll try to get this done before going on vacation :)
