### ISSUE TITLE
about:addons addon installation failed

### ISSUE THREAD

**Issue by RogerHofmann** [SAP/project-foxhound#32]
Hi, 
When trying to install the plugin [taintnotifier-1.1.6-raw.xpi](https://github.tools.sap/dkom2021/HOS8008-HOS8038/raw/master/files/taintnotifier-1.1.6-raw.xpi) I get this error even with xpinstall.signatures.required = false 

<img width="1134" alt="image" src="https://user-images.githubusercontent.com/54936635/156762978-0515deb0-55c6-4e18-99bc-465d896aa6b3.png">

Foxhound cloned and build on Mac and Ubunto  03.03.2022 (error occure on both)

best

Roger

**Comment by tmbrbr** [comment]
Hi, I have had a look at this, I think it can easily fixed by adding the following line to the .mozconfig file:

```
# Add-on signing is not required for DevEdition
MOZ_REQUIRE_SIGNING=
```

For example here: https://github.com/SAP/project-foxhound/blob/main/browser/config/mozconfigs/linux64/devedition

I will prepare a patch for the default configs and provide a fix.

**Comment by RogerHofmann** [comment]
Hi @tmbrbr , it works PlugIn is installed
