### ISSUE TITLE
[Feature Request] Dynamic (de)activation of taint tracking

### ISSUE THREAD

**Issue by vladidx** [SAP/project-foxhound#48]
In certain situations it might be useful to disable and re-enable the taint flow tracking in Foxhound, e.g. if initialization scripts are loaded/executed which should not be considered for tainting before a page navigation to the target URL happens.

Thus, it would be great to have an additional function on the `window` or `document` object that enables to control the taint flow tracking behavior at runtime.

**Comment by tmbrbr** [comment]
I think that using the built in Firefox [Preferences](https://github.com/SAP/project-foxhound/tree/main/modules/libpref) is the way to go here.

Preferences use a key value lookup to get preference values and can be defined at build, start or runtime.

I propose using the folllowing scheme:

```
tainting.sinks.XXX
tainting.sources.XXX
```

where ```XXX``` is the source or sink name, and each prefence can be set as a boolean.
